name: Android APK (Buildozer)

on:
  push:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer (Dockerized)
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ultragod-eafc-omega-apk
          path: bin/*.apk
